
- name: stop_all # noqa: name[casing]
  become: true
  become_user: "{{ ST_USER }}"
  ansible.builtin.command: "sh {{ FILEDRIVEHOME }}/bin/stop_all -f"
  args:
    chdir: "{{ FILEDRIVEHOME }}/bin/"
    executable: /bin/bash
  tags:
    - debug
- name: start_all # noqa: name[casing]
  become: true
  become_user: "{{ ST_USER }}"
  ansible.builtin.shell: "sh {{ FILEDRIVEHOME }}/bin/start_all"
  args:
    chdir: "{{ FILEDRIVEHOME }}/bin/"
    executable: /bin/bash
  tags:
    - debug
# handlers file for st_optimization
