---
- name: Start all
  become: true
  become_user: "{{ ST_USER }}"
  ansible.builtin.shell:
    cmd: "{{ FILEDRIVEHOME }}/bin/start_all"
    executable: /usr/bin/bash
  register: start_services
  changed_when: true

- name: Wait for start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: "{{ SSL_ADMIN_PORT }}"
    delay: 100
    timeout: 600
# handlers file for st_update
