---
- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql-14
    state: restarted
  when: pgconf.changed
- name: Restart postgres
  ansible.builtin.service:
    name: postgresql-14
    state: restarted
# handlers file for postgres-config
