- name: Download and extract the Azure FileStorage plugin
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ AXWAY_HOME }}/SecureTransport/plugins/transferSites/"
    mode: '0755'
    group: "{{ ST_GROUP }}"
    owner: "{{ ST_USER }}"
    validate_certs: false
    remote_src: true
  when:
    - inventory_hostname in groups["cores"]
  tags:
    - st_install
    - axway_lab_specific
  with_items: "{{ plugins }}"